### ISSUE TITLE
Prevent listening to one of fields in formula / only use selector for its value

### ISSUE THREAD

**Issue by LeoZandvliet** [c17r/jAutoCalc#17]
Is it possible to prevent listening to a field used in a formula ?
If not, is it possible to remove that specific listener after starting jAutoCalc ? I think this is the least complex solution to accomplish my goal.

For example the fields:

1. qty
2. price
  Formula: {total} / {qty}
  But I only want a recalculation if the total is changed
3. total
  Formula: {qty} * {price}
 
The listener on qty for field price should be removed, 
while the listener on qty for total should stay.

A fiddle: https://jsfiddle.net/t8soy362/
The total is not changed if the qty changes, because the price is recalculated first.

**Comment by c17r** [comment]
My jQuery knowledge isn't as deep as it used to be but I don't think there is a way you can do this on your own since everything is done namspaced and in the context of the plugin.

I just pushed v1.4.1 to NPM which allows you to defined the equation on price as `jAutoCalc="{total} / {!qty}"` and that particular equation will not listen for changes to the qty field, only total.

**Comment by LeoZandvliet** [comment]
My whole javascript knowledge is very very limited if I see what you've created.
Funny enough I tried your solution already with the 1.3.1 version to check if something like that would have been implemented already. I will try 1.4.1 ! Thank you very much !
