### ISSUE TITLE
How to use other field than input as data source?

### ISSUE THREAD

**Issue by Sima-G** [c17r/jAutoCalc#4]
I want to use other sources as inputs for my calculations. Is it possible?

**Comment by c17r** [comment]
Could you provide an example of what you'd want to use other than an input tag?

**Comment by Sima-G** [comment]
For example a span or a table division..

**Comment by c17r** [comment]
Since those elements can contain other nested elements which they themselves could contain nested elements, there's really no clean way to get the "value" of such a thing.  INPUT/SELECT/etc tags have a definitive value to them.  My recommendation would be to back the SPAN or TD with a INPUT/HIDDEN tag that has the value for this library to use.
