### ISSUE TITLE
Decimal places issue

### ISSUE THREAD

**Issue by jeffreydmain** [c17r/jAutoCalc#7]
Hi there – I am using this plugin for a table in which there's a lot of basic math involving decimals going on, so in order for the math to be accurate, I need 7 decimal places. (i.e. $5.00000).

But, I only want to display 2 decimal places to the user on the front facing table. (i.e. $5.00)

I've read through your documentation and tried some variants of the **decimalPlaces:** option with no luck.

Am I missing something basic here?

    $(document).ready(function() {
    function autoCalcSetup() {  
    $('form[name=cart]').jAutoCalc({decimalPlaces: 7});
    $('form[name=cart] tr[name=line_items]').jAutoCalc({decimalPlaces: 2});
    }
    autoCalcSetup();
    });

It would also be acceptable to show just whole numbers on the result, but in the same way, I was messing with the **smartIntegers** option with no luck.

Thanks in advance!

**Comment by c17r** [comment]
Sorry, this is a repository I look at often anymore. Being 18 months later, I'm sure you either figured something out or moved on, but here's my two cents on it.

The example you gave isn't going to work because you'd need to put more specific config first. `$('form[name=cart]').jAutoCalc({decimalPlaces: 7});` sets everything to be 7 decimals and flags the items as being already set up so when `$('form[name=cart] tr[name=line_items]').jAutoCalc({decimalPlaces: 2});` fires it won't find any fields it can run on.

This library may not be a good fit for this particular use case. The only way I can think of doing what you need would be to have a "shadow structure" with input/hidden fields with the math set for 7 decimal places with the UI fields set for 2.
